#!/bin/bash

dnf install -y samba samba-client samba-common
systemctl start smb
systemctl enable smb
systemctl status smb
firewall-cmd --permanent --add-service=samba --zone=public
firewall-cmd --reload

mkdir -p /var/shares
chmod -R 0777 /var/share
chown -R nobody:nobody /var/share
chcon -t samba_share_t /var/share

cat > /etc/samba/smb.conf << EOF
[global]
        workgroup = WORKGROUP
        netbios name = rhel
        security = user
	map to guest = Bad User
	
[Anonymous]
        comment = Anonymous File Server Share
        path = /srv/samba/anonymous
        browsable =yes
        writable = yes
        guest ok = yes
        read only = no
        force user = nobody
EOF

systemctl restart smb.service
systemctl restart nmb.service
testparm
