#!/bin/bash

dnf install -y samba samba-client samba-common
systemctl start smb
systemctl enable smb
firewall-cmd --permanent --add-service=samba --zone=public
firewall-cmd --reload

echo "Please insert shared folder name?"
read fn
mkdir -p /var/$fn
chmod -R 0777 /var/$fn
chown -R nobody:nobody /var/$fn
chcon -t samba_share_t /var/$fn

echo "Please insert nethbios name?"
read nbm
echo "Please insert workgroup name?"
read wg
mv /etc/samba/smb.conf /etc/samba/smb.conf.ori
cat > /etc/samba/smb.conf << EOF
[global]
        workgroup = $wg
        netbios name = $nbm
        security = user
	map to guest = Bad User
	
[$fn]
        comment = Anonymous File Server Share
        path = /var/$fn
        browsable =yes
        writable = yes
        guest ok = yes
        read only = no
        force user = nobody
EOF

systemctl restart smb.service
systemctl restart nmb.service
testparm
